### ISSUE TITLE
KBFS appears to time out when opening directory

### ISSUE THREAD

**Issue by johnnyRose** [keybase/kbfs#1639]
I noticed this first last Friday, 2018-06-22. When opening a directory on KBFS, it seems to hang and then gives me this error:

> K:\private\johnnyrose\Work refers to a location that is unavailable. It could be on a hard drive on this computer, or on a network. Check to make sure that the disk is properly inserted, or that you are connected to the Internet or your network, and then try again. If it still cannot be located, the information might have been moved to a different location.

When I try again, it can usually navigate into the directory successfully, but when trying to open a file, I get this error:

> K:\private\johnnyrose\Work\doc.txt
> The directory name is invalid.

Occasionally it can successfully open a file, but it usually just errors.

I am experiencing this on Windows 7. I reinstalled Dokan and Keybase last week but it didn't fix the issue.

This seemed to work fine on macOS as of last week and Ubuntu 18 as of today, but fails from this machine regardless of the network.

log id: `da1edc191aba6dcba0e7411c`

**Comment by strib** [comment]
cc @zanderz @taruti

**Comment by zanderz** [comment]
According to the log, Keybase programs remain disconnected from the service, likely fixed with https://github.com/keybase/client/pull/12516. The root cause is installing and/or running Keybase services with elevated permissions.

**Comment by zanderz** [comment]
@johnnyRose please try installing https://prerelease.keybase.io/windows/Keybase_2.1.2-20180625120550%2B836e4aeaca.386.msi and let us know if you still have problems.

**Comment by johnnyRose** [comment]
@zanderz no dice, same issue.

New log id: `ea96762746380e8728455c1c`

**Comment by zanderz** [comment]
This log looks different: kbfs and the gui can talk to the service, but then, in KBFS:
```
130677 2018-06-25T15:55:39.048577-05:00 - [DEBU kbfs fs.go:300] 78a FS Open: ["private" "johnnyrose" "nginx hosting"] [tags:DID=TnZ2G6KKIoCQCI6AgSou8w]
130678 2018-06-25T15:55:39.048577-05:00 - [DEBU kbfs folderlist.go:73] 78b FL Lookup []string{"johnnyrose", "nginx hosting"} type=private upper=false [tags:DID=TnZ2G6KKIoCQCI6AgSou8w]
130679 2018-06-25T15:55:39.048577-05:00 - [DEBU kbfs folderlist.go:108] 78c FL Lookup recursing to child "johnnyrose" [tags:DID=TnZ2G6KKIoCQCI6AgSou8w]
130680 2018-06-25T15:55:39.048577-05:00 - [DEBU kbfs dir.go:284] 78d Dir openDir [nginx hosting] [tags:DID=TnZ2G6KKIoCQCI6AgSou8w]
130681 2018-06-25T15:55:39.048577-05:00 - [DEBU kbfs(FBO d2525233) folder_branch_ops.go:1960] 78e Lookup NodeID(0x18072140) nginx hosting [tags:DID=TnZ2G6KKIoCQCI6AgSou8w]
130682 fatal error: out of memory
130683
130684 runtime stack:
130685 runtime.throw(0x12c1692, 0xd)
130686 C:/Go/src/runtime/panic.go:616 +0x6b
130687 runtime.largeAlloc(0x8023b, 0x1140101, 0x1148220)
130688 C:/Go/src/runtime/malloc.go:828 +0xdc
130689 runtime.mallocgc.func1()
130690 C:/Go/src/runtime/malloc.go:721 +0x39
130691 runtime.systemstack(0x0)
130692 C:/Go/src/runtime/asm_386.s:464 +0x5e
130693 runtime.mstart()
130694 C:/Go/src/runtime/proc.go:1175
130695
130696 goroutine 454 [running]:
130697 runtime.systemstack_switch()
130698 C:/Go/src/runtime/asm_386.s:418 fp=0x16b8f560 sp=0x16b8f55c pc=0x44eab0
130699 runtime.mallocgc(0x8023b, 0x10c58e0, 0x16b8f501, 0x11a84e0)
130700 C:/Go/src/runtime/malloc.go:720 +0x67b fp=0x16b8f5b4 sp=0x16b8f560 pc=0x40fc0b
130701 runtime.makeslice(0x10c58e0, 0x8023b, 0x8023b, 0x0, 0x18082fc0, 0x181297a0)
130702 C:/Go/src/runtime/slice.go:61 +0x59 fp=0x16b8f5c8 sp=0x16b8f5b4 pc=0x43c869
130703 bytes.makeSlice(0x8023b, 0x0, 0x0, 0x0)
130704 C:/Go/src/bytes/buffer.go:230 +0x61 fp=0x16b8f5e4 sp=0x16b8f5c8 pc=0x4dd341
```

**Comment by johnnyRose** [comment]
@zanderz nice catch. Can confirm, the kbfsdokan.exe process eatsmemory until it climbs over 1.5 GB, and then kills my explorer window.

**Comment by strib** [comment]
@johnnyRose are you doing anything to trigger these crashes? Like copying lots of data into or out of KBFS?  Or you're just opening an explorer window and waiting, and it crashes on its own?

In your logs, it seems like a lot of data is being accessed, but I'm not sure if that's by you, or Windows, or maybe some background backup program.

**Comment by johnnyRose** [comment]
@strib all I have to do is open the directory. I don't have the chance to do much else.

**Comment by johnnyRose** [comment]
Looking into the possibility of it being an unknown background program...

**Comment by strib** [comment]
Don't bother, I see something else in the logs.  One sec...

**Comment by strib** [comment]
So it looks like your PC is in a "conflicted" state for that folder, compared to your other devices.  That means at some point you wrote some data in there, at the same time another device wrote data.  Usually this is fine and is automatically fixed in the background, but in this case it seems to be triggering a memory crash on your PC and so it is never fixed.

If you're sure you didn't put anything in the folder from your Windows PC that you can't recover from elsewhere (like your local PC drive), then this is easy to fix the following way:
* Quit the Keybase app, so your L: drive is unmounted.
* Rename the directory `%LOCALAPPDATA%\Keybase\kbfs_journal\v1\01206d1da2426f2c736fea7fc8b4653a87ac-d252523393ec5cdb` to something else, say `d252523393ec5cdb.bkp`.
* Restart the Keybase app.

After that, things should be good and you can restore any data that didn't get merged into the folder from your windows pc.
